apiVersion: v1
kind: Service
metadata:
  name: logging-demo-service
spec:
  selector:
    app: logging-demo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30001
  type: NodePort
